#CLOUD_CONNECTOR_CONNECTED_CLIENT_RECORDER_IMPL="inventory" \
#CLOUD_CONNECTOR_SERVICE_TO_SERVICE_CREDENTIALS="{\"fred\":\"fredskey\"}" \
#CLOUD_CONNECTOR_AUTH_GATEWAY_URL="http://FAKE/" \
#CLOUD_CONNECTOR_AUTH_GATEWAY_HTTP_CLIENT_TIMEOUT="5" \

CLOUD_CONNECTOR_RHC_MESSAGE_KAFKA_BROKERS="localhost:29092" \
CLOUD_CONNECTOR_MQTT_CLIENT_ID="kafka-consumer" \
CLOUD_CONNECTOR_SOURCES_RECORDER_IMPL="fake" \
CLOUD_CONNECTOR_CONNECTED_CLIENT_RECORDER_IMPL="fake" \
CLOUD_CONNECTOR_MQTT_BROKER_TLS_SKIP_VERIFY=true \
CLOUD_CONNECTOR_INVENTORY_KAFKA_BROKERS="localhost:29092" \
CLOUD_CONNECTOR_INVENTORY_KAFKA_TOPIC="platform.inventory.host-ingress" \
CLOUD_CONNECTOR_INVENTORY_KAFKA_BATCH_SIZE="1" \
./cloud-connector kafka_message_consumer -l localhost:8083
