apiVersion: v1
kind: Template
metadata:
  name: cloud-connector-aws
objects:


- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: cloud-connector-aws
      pod: mosquitto-broker-2
    name: mosquitto-broker-2
  spec:
    replicas: 1
    selector:
      matchLabels:
          app: cloud-connector-aws
          pod: mosquitto-broker-2
    revisionHistoryLimit: 10
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: cloud-connector-aws
          pod: mosquitto-broker-2
      spec:
        containers:
          - image: >-
              quay.io/cloudservices/eclipse-mosquitto:latest
            imagePullPolicy: Always
            name: mosquitto-broker-2
            ports:
              - containerPort: 1883
                protocol: TCP
            resources:
              limits:
                cpu: '1'
                memory: 1Gi
              requests:
                cpu: 500m
                memory: 512Mi
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            volumeMounts:
              - mountPath: /mosquitto/config
                name: mosquitto-broker-volume-1
        volumes:
          - configMap:
              defaultMode: 420
              items:
                - key: mosquitto.conf
                  path: mosquitto.conf
              name: mosquitto-config
            name: mosquitto-broker-volume-1
        dnsPolicy: ClusterFirst
        imagePullSecrets:
          - name: quay-cloudservices-pull
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30


- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: mosquitto-config
    labels:
      app: cloud-connector
  data:
    mosquitto.conf: |-
      port 1883
      allow_anonymous true
      ## PATH to ca file
      #cafile /mosquitto/config/certs/ca.pem
      ## PATH to server certificate
      #certfile /mosquitto/config/certs/server_cert.pem
      ## PATH to encoded keyfile
      #keyfile /mosquitto/config/certs/server_key.pem
      ## Certificates required
      #require_certificate true
      ## If Certs are required you can use certs as username
      #use_identity_as_username true
      ## Do not allow anonymous clients
      #allow_anonymous false
      ## Declare acl_file
      #acl_file /mosquitto/config/mosquitto.acl
    mosquitto.acl: |-
      user connector-service
      topic readwrite redhat/insights/#

      # This works
      #pattern readwrite redhat/insights/%c/#

      # This is a bit more strict
      pattern read redhat/insights/%c/out
      pattern write redhat/insights/%c/in


- apiVersion: v1
  kind: Service
  metadata:
    name: mosquitto-2
    labels:
      app: cloud-connector-aws
    annotations:
  spec:
    ports:
    - name: port-1883
      port: 1883
      protocol: TCP
      targetPort: 1883
    selector:
      app: cloud-connector-aws
      pod: mosquitto-broker-2
    sessionAffinity: None
    type: ClusterIP
