{
 "title": "Cloud-Connector",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "aws_resources_exporter", "label": "Resources Exporter", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 20, "x": 0, "y": 0 },
   "options": {
    "content": "<center><h1>Cloud-Connector SLOs</h1></center>"
   }
  },
  {
   "title": "HTTP Availability SLO (95%)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(1.0 - (sum(increase((cloud_connector_http_status_code_counter{service=\"cloud-connector-api\", status_code=~\"5.*\"})[$__range:1m]) or vector(0))/ sum(increase(cloud_connector_http_status_code_counter{service=\"cloud-connector-api\"}[$__range:1m]))) )"
    }
   ]
  },
  {
   "title": " HTTP Latency SLO (90%)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 10, "x": 10, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(cloud_connector_http_response_duration_bucket{le=\"0.25\", status_code=~\"2.*\", service=\"cloud-connector-api\"}[5m])) / sum(increase(cloud_connector_http_response_duration_bucket{le=\"+Inf\", status_code=~\"2.*\", service=\"cloud-connector-api\"}[5m]))"
    }
   ]
  },
  {
   "title": "MQTT Control Message Availability SLO (95%)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(cloud_connector_mqtt_message_consumer_kafka_writer_publish_duration_count[5m])) / sum(rate(cloud_connector_mqtt_control_message_received_count[5m]))"
    }
   ]
  },
  {
   "title": "Kafka Message Consumer Latency SLO (95%)",
   "type": "gauge",
   "description": "95% of messages processed in less than 1 second",
   "gridPos": { "h": 7, "w": 10, "x": 10, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(cloud_connector_kafka_message_wait_time_bucket{le=\"1\"}[5m])) / sum(increase(cloud_connector_kafka_message_wait_time_bucket{le=\"+Inf\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 20, "x": 0, "y": 16 },
   "options": {
    "content": "<center><h1>Cloud-Connector Components</h1></center>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 10, "x": 0, "y": 18 },
   "options": {
    "content": "<center><h1>Cloud-Connector MQTT Consumer</h1></center>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 10, "x": 10, "y": 18 },
   "options": {
    "content": "<center><h1>Cloud-Connector Kafka Consumer</h1></center>"
   }
  },
  {
   "title": "Pod Restarts",
   "type": "stat",
   "gridPos": { "h": 3, "w": 10, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(kube_pod_container_status_restarts_total{container=\"cloud-connector-mqtt-message-consumer\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Pod Restarts",
   "type": "stat",
   "gridPos": { "h": 3, "w": 10, "x": 10, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(kube_pod_container_status_restarts_total{container=\"cloud-connector-api\"}[$__range]))"
    }
   ]
  },
  {
   "title": "MQTT Control Messages Consumed Per Minute",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "sum(increase(cloud_connector_mqtt_control_message_received_count[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kafka Messages Lag",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 10, "y": 23 },
   "targets": [
    {
     "expr": "sum by(consumer_group, topic) (aws_kafka_sum_offset_lag_sum{topic=~\"platform.cloud-connector.rhc-message-ingress\"})"
    }
   ]
  },
  {
   "title": "MQTT Message Consumed",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "rate(cloud_connector_mqtt_control_message_received_count[1m]) + rate(cloud_connector_mqtt_data_message_received_count[1m])"
    }
   ]
  },
  {
   "title": "Kafka Messages Consumed Per Minute",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 10, "y": 29 },
   "targets": [
    {
     "expr": "sum(rate(cloud_connector_kafka_message_received_count[1m]))"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{container=\"cloud-connector-mqtt-message-consumer\"}[1m])"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{container=\"cloud-connector-mqtt-message-consumer\"}"
    }
   ]
  },
  {
   "title": "Inventory Messages Produced Per Minute",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(cloud_connector_inventory_kafka_writer_success_count[1m]))"
    }
   ]
  },
  {
   "title": "Inventory Messages Failed Per Minute",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 15, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(cloud_connector_inventory_kafka_writer_failure_count[1m]))"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{container=\"cloud-connector-kafka-message-consumer\"}[1m])"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 15, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{container=\"cloud-connector-kafka-message-consumer\"}"
    }
   ]
  },
  {
   "title": "Go Routines",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_goroutines{namespace=~\"cloud-connector-.*\",pod=~\"cloud-connector-mqtt-.*\"}"
    }
   ]
  },
  {
   "title": "Go Routines",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 10, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_goroutines{namespace=~\"cloud-connector-.*\",pod=~\"cloud-connector-kafka-.*\"}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 10, "x": 0, "y": 48 },
   "options": {
    "content": "<center><h1>Cloud-Connector API Service</h1></center>"
   }
  },
  {
   "title": "Pod Restarts",
   "type": "stat",
   "gridPos": { "h": 3, "w": 10, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(kube_pod_container_status_restarts_total{container=\"cloud-connector-api\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Kafka Inventory Writer Go Routine Metrics - 5m",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 10, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg_over_time(cloud_connector_inventory_kafka_writer_go_routine_count{container=\"cloud-connector-kafka-message-consumer\"}[5m])"
    },
    {
     "expr": "max_over_time(cloud_connector_inventory_kafka_writer_go_routine_count{container=\"cloud-connector-kafka-message-consumer\"}[5m])"
    }
   ]
  },
  {
   "title": "MQTT Messages Sent Per Minute",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(cloud_connector_mqtt_message_published_success_count[1m]))"
    }
   ]
  },
  {
   "title": "MQTT Messages Sent Failed Per Minute",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(cloud_connector_mqtt_message_published_failure_count[1m]))"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{container=\"cloud-connector-api\"}[1m])"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{container=\"cloud-connector-api\"}"
    }
   ]
  },
  {
   "title": "Go Routines",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_goroutines{namespace=~\"cloud-connector-.*\",pod=~\"cloud-connector-api-.*\"}"
    }
   ]
  },
  {
   "title": "RDS storage usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rdsosmetrics_fileSys_usedPercent{mount_point=\"/rdsdbdata\", exported_instance=~\"cloud-connector-.*\"}",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  }
 ]
}