---
name: PR Check

on:
  push:
    branches:
      - master
  pull_request:
    types: ["opened", "synchronize", "reopened"]

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.18.x, 1.19.x]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Run Tests
      run: go test ./...
