---
name: PR Check

on:
  - pull_request

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.25.9]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v5
    - name: Install Go
      uses: actions/setup-go@v6
      with:
        go-version: ${{ matrix.go-version }}
    - name: Run Tests
      run: go test -v ./...
