---
name: PR Check

on:
  - pull_request

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.15.x, 1.16.x]
        os: ubuntu-latest
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: ${{github.event.pull_request.head.ref}}
        repository: ${{github.event.pull_request.head.repo.full_name}}
    - name: Run Tests
      run: go test ./...
